openapi: 3.1.0
info:
  title: Alpaca API Wrapper
  version: 1.0.0
servers:
  - url: https://alpaca-api-wrapper.onrender.com
paths:
  /aapl/10min:
    get:
      summary: Get AAPL 10min chart
      operationId: getAAPL10min
      responses:
        '200':
          description: AAPL 10min data
  /aapl/1hour:
    get:
      summary: Get AAPL 1hour chart
      operationId: getAAPL1hour
      responses:
        '200':
          description: AAPL 1hour data
  /aapl/4hour:
    get:
      summary: Get AAPL 4hour chart
      operationId: getAAPL4hour
      responses:
        '200':
          description: AAPL 4hour data
  /aapl/1day:
    get:
      summary: Get AAPL 1day chart
      operationId: getAAPL1day
      responses:
        '200':
          description: AAPL 1day data
  /aapl/1week:
    get:
      summary: Get AAPL 1week chart
      operationId: getAAPL1week
      responses:
        '200':
          description: AAPL 1week data
